### ISSUE TITLE
JOIN-queries are not working

### ISSUE THREAD

**Issue by vinograt** [bobfreitas/hiveunit-mr2#3]
I've tried to run some query with two or more tables like this: 
`SELECT * FROM today t, snapshot s;`
but got an exception:

```
2016-10-24 16:35:27,988 INFO  [main] mr.MapredLocalTask (MapredLocalTask.java:executeInChildVM(287)) - Executing: /usr/bin/hadoop jar /Users/vinogradov/.gradle/caches/modules-2/files-2.1/org.apache.hive/hive-exec/1.1.0/63339871f0b4999e84eb51bafbf62cd48b6f9486/hive-exec-1.1.0.jar org.apache.hadoop.hive.ql.exec.mr.ExecDriver -localtask -plan file:/var/folders/pb/3b7vdcds29dgx3mbkvn4dllm0000gn/T/1477316097162-0/scratch/b4353065-eaa6-47be-a968-0c93696f86f0/hive_2016-10-24_16-35-27_621_2782908466895847003-1/-local-10005/plan.xml   -jobconffile file:/var/folders/pb/3b7vdcds29dgx3mbkvn4dllm0000gn/T/1477316097162-0/scratch/b4353065-eaa6-47be-a968-0c93696f86f0/hive_2016-10-24_16-35-27_621_2782908466895847003-1/-local-10006/jobconf.xml
2016-10-24 16:35:27,992 ERROR [main] mr.MapredLocalTask (MapredLocalTask.java:executeInChildVM(318)) - Exception: Cannot run program "/usr/bin/hadoop" (in directory "/Users/***/***/hive"): error=2, No such file or directory
java.io.IOException: Cannot run program "/usr/bin/hadoop" (in directory "/Users/***/***/hive"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask.executeInChildVM(MapredLocalTask.java:290)
    at org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask.execute(MapredLocalTask.java:139)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:160)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:88)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1638)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1397)
    at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1183)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1049)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1039)
    at com.inmobi.hive.test.HiveTestCluster.processStatement(HiveTestCluster.java:99)
    at com.inmobi.hive.test.HiveTestCluster.executeStatements(HiveTestCluster.java:78)
    at com.inmobi.hive.test.HiveTestSuite.executeScript(HiveTestSuite.java:66)
    at com.inmobi.hive.test.HiveTestSuite.executeScript(HiveTestSuite.java:52)
    at com.***.hive.func.TotalNumOfLettersGenericUDAFTest.theSecondTest(TotalNumOfLettersGenericUDAFTest.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 40 more
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask
```

**Comment by vinograt** [comment]
As I understand there is no MR-cluster to run this query. How can I start one with `HiveTestSuite`?

**Comment by bobfreitas** [comment]
Hi Vinograt,

There is a cluster running.  It is a memory resident cluster, so everything
runs in memory.  You need to properly stage your data using a very small
sample of data.  Not sure what you are doing by just the stack trace.  But
just off the cuff, the error message of no file or directory might mean
there is no underlying table.  Did you properly stage your data?  You need
to copy some data from the local filesystem to the memory resident HDFS,
create your table, and then you can run the query.

Best of luck to you,
Bob

**Comment by vinograt** [comment]
Hi Bob! I'm very appreciated you implementing this helpful library.

I stage my very small amount of data to HDFS with the following code:
```
Map<String, String> params = new HashMap<>();
copyToHdfs("src/test/resources/files/snapshot.txt", "/testing/snapshot/snapshot.txt");
params.put("SNAPSHOT_DATA", "/testing/snapshot");
copyToHdfs("src/test/resources/files/today.txt", "/testing/today/today.txt");
params.put("TODAY_DATA", "/testing/today");
```
I create external tables for each the data set with:
```
CREATE EXTERNAL TABLE snapshot (user_id STRING, calls_num STRING, calls_duration STRING)
ROW FORMAT DELIMITED FIELDS
	TERMINATED BY ';'
	ESCAPED BY ''
	LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '${SNAPSHOT_DATA}';

CREATE EXTERNAL TABLE today (id STRING, user_id STRING, payload STRING)
ROW FORMAT DELIMITED FIELDS
	TERMINATED BY ','
	ESCAPED BY ''
	LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '${TODAY_DATA}';
```
I can run queries like these:
```
SELECT * FROM snapshot;
SELECT user_id, calls_duration(payload) FROM today GROUP BY user_id;
```
But I cannot run it:
```
SELECT * FROM today, snapshot;
```
An exception was described above.

**Comment by martinprobson** [comment]
Hello Bob/vinograt,
I know this is an old issue, but I have just forked this code and had the same problem. Setting the following parameters just before the join solved it for me: -
```
set hive.auto.convert.join=false;
set hive.auto.convert.join.noconditionaltask=false;
```

I think without these parms, Hive is trying to do a map-side join which will fail. With these params set a normal shuffle join is attempted which seems to work fine.
Hope it works for you as well.

Regards,
Martin

**Comment by bobfreitas** [comment]
@martinprobson  awesome!  do you want to merge it into my master, happy to include you?
I really gotta revisit this project

**Comment by martinprobson** [comment]
Hi Bob, Happy to do that, will prepare a pull request.

Regards,
Martin
